name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  Build_and_Ship_Docker:

    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag gradle-app:$(date +%s)

    - name: Publish Docker Image to GitHub Registry
      uses: TilBlechschmidt/gp-docker-action@v0.2-alpha
      with:
        # GitHub token to push Docker image to GitHub Packages
        github-token: ${{ secrets.DOCKER_REGISTRY }}
        image-name: gradle-app
        image-tag: latest

    - name: Deploy Docker by SSH
      uses: appleboy/ssh-action@v0.1.4
      with:
        # ssh host
        host: 54.69.231.212
        username: ec2-user
        key: ${{ secrets.SSH_KEY }}
        # # path of ssh private key
        # key_path: # optional
        script: docker ps
        debug: true
